// <auto-generated />
using Cadastro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cadastro.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230617045238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cadastro.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Cpf")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Preferencia")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = 30145952096L,
                            Email = "lucas@gmail.com",
                            Nome = "Lucas",
                            Preferencia = 1,
                            Senha = "lucas312"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = 50730307026L,
                            Email = "jorge@gmail.com",
                            Nome = "Jorge",
                            Preferencia = 2,
                            Senha = "jorge123"
                        },
                        new
                        {
                            Id = 3,
                            Cpf = 34329462010L,
                            Email = "davi@outlook.com",
                            Nome = "Davi",
                            Preferencia = 3,
                            Senha = "davi321"
                        },
                        new
                        {
                            Id = 4,
                            Cpf = 27730060035L,
                            Email = "maria@hotmail.com",
                            Nome = "Maria",
                            Preferencia = 4,
                            Senha = "maria231"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
